services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: document_vault
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"